services:
  opentracker:
    image: wiltonsr/opentracker:open
    ports:
      - "6969:6969"
      - "6969:6969/udp"
    restart: unless-stopped


  qbittorrent:
    image: linuxserver/qbittorrent:latest
    environment:
      - PUID=1000
      - PGID=1000
      - WEBUI_PORT=8080
    ports:
      - "8080:8080"
      - "6881:6881"
      - "6881:6881/udp"
    volumes:
      - ./docker/qbittorrent/config:/config
      - ./docker/qbittorrent/downloads:/downloads
      - ./docker/torrents:/torrents
    restart: unless-stopped
  bittorrent-client:
    build: src-tauri
    depends_on:
      - opentracker
    volumes:
      - ./docker/torrents:/torrents